# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffbcd3bb892e621ad95ac8db428d9bace7b9420ca61d8ebb0be2ac98e6534370a4dbec531c864fed4d878e3401bb352bf568e027c81dbbbcea5e93228d634e6e

test:
  secret_key_base: ae5fac81f0a727100eb75538d9550cc696f335e4c706defa596ba111bd4aa0349f734ced3a4dc0f75aeac931258dd0ca38a2ff653e54ff538ab82a9c3e57058b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
